# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up .env variables
        run: |

          JSON_STRING=$(sed 's/\s//g' <<< "${{ secrets.MY_SECRET_TEST }}")
          export TEST_BAKI="${{ fromJSON(JSON_STRING).TEST_BAKI }}"
          export TEST_TAKI="${{ fromJSON(JSON_STRING).TEST_TAKI }}"
          export TEST_MOHAMED="${{ fromJSON(JSON_STRING).TEST_MOHAMED }}"
          export TEST_YASMINA="${{ fromJSON(JSON_STRING).TEST_YASMINA }}"
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: install project dependecies
        run: npm ci
      - name: Run unit test
        run: npm run test
